steps:
  # test it
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t","mtgfail-test:$SHORT_SHA", ".", "-f ", "Dockerfile.test"]
  # build it and push it
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/snackend/mtgfail:$SHORT_SHA", "."]
  images: ['gcr.io/gcr.io/snackend/mtgfail:$SHORT_SHA']
  # tag it latest and push it
- name: "gcr.io/cloud-builders/docker"
  args: ["tag", "gcr.io/snackend/mtgfail:$SHORT_SHA", "gcr.io/snackend/mtgfail:latest"]
  images: ['gcr.io/gcr.io/snackend/mtgfail:latest']
  # deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=deployment.yml
  - --image=gcr.io/snackend/mtgfail:$SHORT_SHA
  - --location=us-central1-c
  - --cluster=cluster-1
