[deck]
cmdr = "Dalakos, Crafter of Wonders"
[deck.cards]                             
"Bloodstained Mire"                               =                         1 
"Command Tower"                                   =                         1 
"Fabled Passage"                                  =                         1 
"Flooded Strand"                                  =                         1 
"Great Furnace"                                   =                         1 
"Island"                                          =                         19
"Mountain"                                        =                         6 
"Mystic Sanctuary"                                =                         1 
"Polluted Delta"                                  =                         1 
"Seat of the Synod"                               =                         1 
"Steam Vents"                                     =                         1 
"Sulfur Falls"                                    =                         1 
"Temple of the False God"                         =                         1 
"Wooded Foothills"                                =                         1 
"Anticipate"                                      =                         1 
"Arcane Signet"                                   =                         1 
"Argentum Armor"                                  =                         1 
"Armory Automaton"                                =                         1 
"Basilisk Collar"                                 =                         1 
"Batterskull"                                     =                         1 
"Bloodforged Battle-Axe"                          =                         1 
"Brainstorm"                                      =                         1 
"Brass Squire"                                    =                         1 
"Chaos Warp"                                      =                         1 
"Counterspell"                                    =                         1 
"Cyclonic Rift"                                   =                         1 
"Dalakos, Crafter of Wonders"                     =                         1 
"Deadeye Quartermaster"                           =                         1 
"Divination"                                      =                         1 
"Dramatic Reversal"                               =                         1 
"Echo Storm"                                      =                         1 
"Emry, Lurker of the Loch"                        =                         1 
"Etherium Sculptor"                               =                         1 
"Fabricate"                                       =                         1 
"Foundry Inspector"                               =                         1 
"Goblin Engineer"                                 =                         1 
"Hammer of Nazahn"                                =                         1 
"Herald of Kozilek"                               =                         1 
"Isochron Scepter"                                =                         1 
"Izzet Signet"                                    =                         1 
"Jhoira, Weatherlight Captain"                    =                         1 
"Kazuul's Toll Collector"                         =                         1 
"Mask of Memory"                                  =                         1 
"Mind Stone"                                      =                         1 
"Mirran Spy"                                      =                         1 
"Mirrormade"                                      =                         1 
"Mystic Repeal"                                   =                         1 
"Narset's Reversal"                               =                         1 
"Negate"                                          =                         1 
"Nettle Drone"                                    =                         1 
"Neurok Stealthsuit"                              =                         1 
"Rapid Hybridization"                             =                         1 
"Reality Shift"                                   =                         1 
"Rhystic Study"                                   =                         1 
"Saheeli, Sublime Artificer"                      =                         1 
"Saheeli, the Gifted"                             =                         1 
"Sai, Master Thopterist"                          =                         1 
"Scytheclaw"                                      =                         1 
"Shadowspear"                                     =                         1 
"Skullclamp"                                      =                         1 
"Sol Ring"                                        =                         1 
"Solemn Simulacrum"                               =                         1 
"Swan Song"                                       =                         1 
"Sword of Feast and Famine"                       =                         1 
"Sword of the Animist"                            =                         1 
"Talisman of Creativity"                          =                         1 
"Tezzeret the Seeker"                             =                         1 
"Tezzeret, Artifice Master"                       =                         1 
"Thopter Spy Network"                             =                         1 
"Thoughtcast"                                     =                         1 
"Trailblazer's Boots"                             =                         1 
"Trinket Mage"                                    =                         1 
"Trophy Mage"                                     =                         1 
"Unwinding Clock"                                 =                         1 
"Vandalblast"                                     =                         1 
"Vedalken Engineer"                               =                         1 
"Zephyr Scribe"                                   =                         1
