apiVersion: apps/v1
kind: Deployment
metadata:
  name: mtgfail-api
  namespace: mtgfail
  labels:
    app: mtgfail-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mtgfail-api
  template:
    metadata:
      labels:
        app: mtgfail-api
    spec:
      containers:
      - name: mtgfail-api
        image: gcr.io/snackend/mtgfail:6c0120d
        resources:
          limits:
            memory: "3G"
            cpu: "1"
          requests:
            memory: "1024Mi"
            cpu: "250m"
        ports:
        - containerPort: 8080
---
kind: Service 
apiVersion: v1 
metadata:
  name: mtgfail-api
  namespace: mtgfail
spec:
  type: NodePort
  selector:
    app: mtgfail-api
  ports:
    - nodePort:
      port: 8080
      targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.gcp.kubernetes.io/pre-shared-cert: mcrt-de6a3a52-77d4-4aa0-8ba9-b919a02c8d68
    networking.gke.io/managed-certificates: api-mtg-fail
  name: mtgfail-api
  namespace: mtgfail
spec:
  backend:
    serviceName: mtgfail-api
    servicePort: 8080
status:
  loadBalancer: {}
