apiVersion: apps/v1
kind: Deployment
metadata:
  name: mtgfail-api
  namespace: mtgfail
  labels:
    app: mtgfail-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mtgfail-api
  template:
    metadata:
      labels:
        app: mtgfail-api
    spec:
      containers:
      - name: mtgfail-api
        image: gcr.io/snackend/mtgfail:6c0120d
        resources:
          limits:
            memory: "3G"
            cpu: "1"
          requests:
            memory: "1024Mi"
            cpu: "250m"
        ports:
        - containerPort: 8080
---
kind: Service 
apiVersion: v1 
metadata:
  name: mtgfail-api
  namespace: mtgfail
spec:
  type: NodePort
  selector:
    app: mtgfail-api
  ports:
    - nodePort:
      port: 8080 
      targetPort: 80
