apiVersion: apps/v1
kind: Deployment
metadata:
  name: mtgfail-api
  namespace: mtgfail
  labels:
    app: mtgfail-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mtgfail-api
  template:
    metadata:
      labels:
        app: mtgfail-api
    spec:
      containers:
      - name: mtgfail-api
        image: gcr.io/snackend/mtgfail:6c0120d
        resources:
          limits:
            memory: "3G"
            cpu: "1"
          requests:
            memory: "1024Mi"
            cpu: "250m"
        ports:
        - containerPort: 8080
---
kind: Service 
apiVersion: v1 
metadata:
  name: mtgfail-api
  namespace: mtgfail
spec:
  type: NodePort
  selector:
    app: mtgfail-api
  ports:
    - nodePort:
      port: 8080
      targetPort: 8080
---
metadata:
  name: {{.app}}-{{.env}}-ingress
  annotations:
    kubernetes.io/ingress.allow-http: "false"          # Enable port 80 access
    kubernetes.io/ingress.global-static-ip-name: "mtgfail" # Name of the static global IP address in GCP
    ingress.gcp.kubernetes.io/pre-shared-cert: mcrt-de6a3a52-77d4-4aa0-8ba9-b919a02c8d68
spec:
  rules:
    - host: api.mtg.fail
      http:
        paths:
          - path: */
            backend:
              serviceName: mtgfail-api
              servicePort: 8080
