FROM golang:1.13-alpine

RUN apk update && apk --no-cache add ca-certificates git && update-ca-certificates

ENV CGO_ENABLED=0
RUN mkdir /go/src/app 
ADD . /go/src/app/
WORKDIR /go/src/app
RUN wget https://archive.scryfall.com/json/scryfall-default-cards.json 

RUN go test -v ./...
